"""Job fixture: the ten factory openings, round-robined onto the companies."""

from __future__ import annotations

from app.models.company import Company
from app.models.job import Job, JobStatus

from .common import new_uuid


def make_jobs(companies: list[Company]) -> list[Job]:
    specs = [
        (
            "Công nhân sản xuất LCD",
            "Hải Phòng",
            "Thành phố Hồ Chí Minh",
            None,
            7_000_000,
            12_000_000,
            "Ca 3 vòng / Ca 4 vòng",
            "Nam/Nữ",
            18,
            45,
            "Không yêu cầu kinh nghiệm",
            True,
            True,
            True,
            50,
        ),
        (
            "Công nhân Assembly",
            "Bắc Ninh",
            "Thuận Thành",
            None,
            7_500_000,
            13_000_000,
            "Ca 3 vòng",
            "Nam/Nữ",
            18,
            40,
            "Không yêu cầu kinh nghiệm",
            True,
            True,
            True,
            80,
        ),
        (
            "Công nhân SMT",
            "Bắc Ninh",
            "Yên Phong",
            None,
            7_000_000,
            11_000_000,
            "Ca 3 vòng / Ca 2 vòng",
            "Nam ưu tiên",
            18,
            45,
            "Không yêu cầu",
            True,
            True,
            True,
            120,
        ),
        (
            "QC/KCS chất lượng",
            "Bắc Ninh",
            "Yên Phong",
            None,
            8_500_000,
            14_000_000,
            "Ca ngày",
            "Nam/Nữ",
            20,
            35,
            "1 năm kinh nghiệm QC",
            True,
            True,
            False,
            15,
        ),
        (
            "Kỹ thuật bảo trì",
            "Hải Phòng",
            "An Dương",
            None,
            10_000_000,
            18_000_000,
            "Ca ngày",
            "Nam",
            22,
            45,
            "2 năm kinh nghiệm bảo trì thiết bị",
            True,
            True,
            False,
            10,
        ),
        (
            "Công nhân đóng gói",
            "Bắc Ninh",
            "Quế Võ",
            None,
            6_500_000,
            9_000_000,
            "Ca 2 vòng",
            "Nữ ưu tiên",
            18,
            40,
            "Không yêu cầu",
            False,
            True,
            True,
            60,
        ),
        (
            "Công nhân lắp ráp điện tử",
            "Nghệ An",
            "TX Hoàng Mai",
            None,
            6_500_000,
            10_000_000,
            "Ca 3 vòng",
            "Nam/Nữ",
            18,
            45,
            "Không yêu cầu kinh nghiệm",
            True,
            True,
            True,
            90,
        ),
        (
            "Tổ trưởng sản xuất",
            "Hải Phòng",
            "Thành phố Hồ Chí Minh",
            None,
            15_000_000,
            22_000_000,
            "Ca ngày",
            "Nam/Nữ",
            25,
            50,
            "3 năm kinh nghiệm, biết quản lý line",
            True,
            True,
            False,
            5,
        ),
        (
            "Kỹ thuật viên",
            "Nghệ An",
            "TX Hoàng Mai",
            None,
            9_000_000,
            15_000_000,
            "Ca ngày",
            "Nam",
            20,
            40,
            "1 năm kinh nghiệm sửa chữa máy móc",
            True,
            True,
            False,
            12,
        ),
        (
            "Công nhân kho vận",
            "Bắc Ninh",
            "Yên Phong",
            None,
            7_000_000,
            10_000_000,
            "Ca ngày",
            "Nam",
            18,
            45,
            "Không yêu cầu",
            False,
            True,
            True,
            20,
        ),
    ]
    jobs: list[Job] = []
    for i, (
        title,
        province,
        district,
        address,
        sal_min,
        sal_max,
        shift,
        gender,
        age_min,
        age_max,
        exp,
        accom,
        meal,
        transport,
        vacancy,
    ) in enumerate(specs):
        company = companies[i % len(companies)]
        jobs.append(
            Job(
                id=new_uuid(),
                company_id=company.id,
                title=title,
                factory_name=company.name,
                province=province,
                district=district,
                address=address,
                salary_min=sal_min,
                salary_max=sal_max,
                shift=shift,
                gender_requirement=gender,
                age_min=age_min,
                age_max=age_max,
                experience_required=exp,
                accommodation_support=accom,
                meal_support=meal,
                transport_support=transport,
                vacancy_count=vacancy,
                status=JobStatus.ACTIVE,
                description=f"Tuyển {vacancy} {title} làm việc tại {province}. {shift}, "
                f"lương {sal_min // 1_000_000}-{sal_max // 1_000_000} triệu.",
                requirements=f"Tuổi {age_min}-{age_max}. {exp}. Ưu tiên biết đọc số, làm việc nhóm.",
                benefits="Bảo hiểm xã hội, sức khỏe, thất nghiệp. Thưởng tháng 13. Đóng góp quỹ hưu trí.",
            )
        )
    return jobs
