schema_version: "1.0"
category: requirements
requirements: []
#  - id: dieu-kien-cong-nhan
#    job_ids: [cong-nhan-san-xuat]
#    age_min: 18
#    age_max: 40
#    genders: [any]  # female|male|any
#    education: Tốt nghiệp THCS
#    experience: Không yêu cầu
#    health: []
#    skills: []
#    required_documents: []
#    other: []
