"""Database-backed integration settings with encrypted secret values.

Public API: ``IntegrationSettingsService`` (a facade composing the storage
primitives and the Zalo / LLM / Facebook provider groups) and
``IntegrationSettingsCipher``; importers should depend on
``app.services.integration_settings`` rather than the internal submodules.
"""

from app.services.integration_settings._shared import (
    LLM_DEFAULT_PROVIDER,
    LLM_FAILOVER_ORDER,
    normalize_llm_failover_order,
)
from app.services.integration_settings.cipher import IntegrationSettingsCipher
from app.services.integration_settings.providers.facebook import (
    FB_APP_ID,
    FB_APP_SECRET,
    FB_LOGIN_CONFIG_ID,
    FB_PAGE_TOKEN_PREFIX,
    FB_SECRET_KEYS,
    FB_SETTING_KEYS,
    FB_WEBHOOK_VERIFY_TOKEN,
    FacebookOAuthConfig,
    FacebookRuntimeConfig,
)
from app.services.integration_settings.providers.llm import (
    CUSTOM_LLM_AGENT_MODEL,
    CUSTOM_LLM_API_KEY,
    CUSTOM_LLM_BASE_URL,
    CUSTOM_LLM_ENABLE,
    CUSTOM_LLM_FAST_MODEL,
    CUSTOM_LLM_LABEL,
    CUSTOM_LLM_SAFETY_MODEL,
    CUSTOM_LLM_SETTING_KEYS,
    JEV_API_KEY,
    JEV_DEFAULT_MODEL,
    JEV_ENABLE,
    JEV_MODEL,
    JEV_SECRET_KEYS,
    JEV_SETTING_KEYS,
    MINIMAX_API_KEY,
    MINIMAX_ENABLE,
    MINIMAX_SETTING_KEYS,
    OPENROUTER_AGENT_MODEL,
    OPENROUTER_API_KEY,
    OPENROUTER_DIGEST_MODEL,
    OPENROUTER_ENABLE,
    OPENROUTER_SAFETY_MODEL,
    OPENROUTER_SETTING_KEYS,
    CustomLlmRuntimeConfig,
    JevRuntimeConfig,
    MinimaxRuntimeConfig,
    OpenRouterRuntimeConfig,
)
from app.services.integration_settings.providers.zalo import (
    ZALO_BOT_TOKEN,
    ZALO_BOT_WEBHOOK_SECRET,
    ZALO_OA_ACCESS_TOKEN,
    ZALO_OA_APP_ID,
    ZALO_OA_REFRESH_LOCK_KEY,
    ZALO_OA_REFRESH_TOKEN,
    ZALO_OA_SECRET_KEY,
    ZALO_OA_TOKEN_URL,
    ZALO_SETTING_KEYS,
    ZaloRuntimeConfig,
)
from app.services.integration_settings.service import IntegrationSettingsService
from app.services.integration_settings.storage import PROVIDER_TEST_KEYS

__all__ = [
    "CUSTOM_LLM_AGENT_MODEL",
    "CUSTOM_LLM_API_KEY",
    "CUSTOM_LLM_BASE_URL",
    "CUSTOM_LLM_ENABLE",
    "CUSTOM_LLM_FAST_MODEL",
    "CUSTOM_LLM_LABEL",
    "CUSTOM_LLM_SAFETY_MODEL",
    "CUSTOM_LLM_SETTING_KEYS",
    "FB_APP_ID",
    "FB_APP_SECRET",
    "FB_LOGIN_CONFIG_ID",
    "FB_PAGE_TOKEN_PREFIX",
    "FB_SECRET_KEYS",
    "FB_SETTING_KEYS",
    "FB_WEBHOOK_VERIFY_TOKEN",
    "FacebookOAuthConfig",
    "FacebookRuntimeConfig",
    "IntegrationSettingsCipher",
    "IntegrationSettingsService",
    "JEV_API_KEY",
    "JEV_DEFAULT_MODEL",
    "JEV_ENABLE",
    "JEV_MODEL",
    "JEV_SECRET_KEYS",
    "JEV_SETTING_KEYS",
    "LLM_DEFAULT_PROVIDER",
    "LLM_FAILOVER_ORDER",
    "MINIMAX_API_KEY",
    "MINIMAX_ENABLE",
    "MINIMAX_SETTING_KEYS",
    "OPENROUTER_AGENT_MODEL",
    "OPENROUTER_API_KEY",
    "OPENROUTER_DIGEST_MODEL",
    "OPENROUTER_ENABLE",
    "OPENROUTER_SAFETY_MODEL",
    "OPENROUTER_SETTING_KEYS",
    "PROVIDER_TEST_KEYS",
    "ZALO_BOT_TOKEN",
    "ZALO_BOT_WEBHOOK_SECRET",
    "ZALO_OA_ACCESS_TOKEN",
    "ZALO_OA_APP_ID",
    "ZALO_OA_REFRESH_LOCK_KEY",
    "ZALO_OA_REFRESH_TOKEN",
    "ZALO_OA_SECRET_KEY",
    "ZALO_OA_TOKEN_URL",
    "ZALO_SETTING_KEYS",
    "CustomLlmRuntimeConfig",
    "JevRuntimeConfig",
    "MinimaxRuntimeConfig",
    "OpenRouterRuntimeConfig",
    "ZaloRuntimeConfig",
    "normalize_llm_failover_order",
]
